apiVersion: v1
kind: PersistentVolume
metadata:
 name: gcp-filestore
spec:
 capacity:
   storage: 2T
 accessModes:
 - ReadWriteMany
 storageClassName: gcp-filestore-pd
 nfs:
   path: /share1
   server: 10.203.50.242