apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: gcp-filestore-setup-claim
spec:
  accessModes:
  - ReadWriteMany
  volumeName: gcp-filestore
  storageClassName: gcp-filestore-pd
  resources:
    requests:
      storage: 100Mi